export { flow, optional } from "./builder";
export {
  type CanonicalDag,
  type CanonicalMatchArm,
  type CanonicalRetryPolicy,
  type CanonicalSchema,
  type CanonicalStep,
  canonicalize,
  fingerprintFlows,
  sha256Canonical,
} from "./canonicalize";
export {
  diffSnapshots,
  type SnapshotChangedEdge,
  type SnapshotChangedField,
  type SnapshotDiff,
} from "./diff";
export {
  NagiCanceledError,
  NagiConcurrencyConflictError,
  NagiFlowSnapshotGoneError,
  NagiNonRetryableError,
  NagiRuntimeError,
  NagiSignalTimeoutError,
  NagiSnapshotDriftError,
  NagiStepTimeoutError,
  NagiValidationError,
} from "./errors";
export { type RowDelta, rowDeltaOf } from "./facts";
export {
  DEFAULT_REAPER_INTERVAL_MS,
  decideExpiredLeaseAction,
  type ReapedLease,
  type ReaperDecision,
} from "./lease-reaper";
export {
  InMemoryClock,
  InMemoryQueue,
  InMemoryStore,
  projectRunState,
} from "./memory";
export { defaultSnapshotGonePolicy } from "./retry";
// Reusable by Store adapters: the chunk fan-out is process-local machinery, not
// a persistence concern, so every adapter drives this same hub rather than
// reimplementing subscriber buffering and close semantics.
export {
  InMemoryRunEventHub,
  isTerminalRunEvent,
  runEventOf,
} from "./run-events";
export { RunId } from "./run-id";
export type {
  RunDescription,
  RunView,
  StepRunStatus,
  StepView,
} from "./run-view";
export {
  type NagiConfig,
  type NagiRunConfig,
  nagi,
  type RuntimeHandle,
  type StartOpts,
  type StartStagedOpts,
  type StartStagedResult,
  type Wf,
} from "./runtime";
export {
  decideSignal,
  decideTimeout,
  type SignalDecision,
  type TimeoutDecision,
} from "./signals";
export type {
  Resolved,
  RunCancelCause,
  RunPhase,
  RunState,
  SkipReason,
  StepCancelCause,
  StepState,
} from "./state";
export {
  attemptOf,
  errorOf,
  isStepTerminal,
  isTerminalRun,
  outputOf,
  resolvedOf,
  runStatusOf,
  stepStateOf,
  stepStatusOf,
  unwrap,
} from "./state";
export { NagiAbortError } from "./step-exec";
export {
  clampQueryLimit,
  compareRunOrder,
  DEFAULT_SWEEP_LIMIT,
  decodeRunCursor,
  encodeRunCursor,
  type FactEffects,
  factEffects,
  isPastCursor,
  jsonContains,
  type PruneCandidate,
  QUERY_RUNS_DEFAULT_LIMIT,
  QUERY_RUNS_MAX_LIMIT,
  type RunCursor,
  selectExpired,
  selectPruneBatch,
} from "./store-policy";
export {
  InMemoryStreamHub,
  STREAM_REPLAY_BUFFER_CAP,
  STREAM_SUBSCRIBER_BUFFER_CAP,
} from "./stream-hub";
// Explicit public type surface (not `export type *`): a new type in types.ts is
// internal-by-default, and any change to the public surface shows up as a diff.
export type {
  AttemptNumber,
  BackoffStrategy,
  Builder,
  CancelArgs,
  ClaimToken,
  Clock,
  ConcurrencyMode,
  DriftPolicy,
  Fact,
  FactKind,
  Flow,
  FlowCanceledByConcurrencyFact,
  FlowCanceledByOperatorFact,
  FlowCanceledExplicitlyFact,
  FlowCanceledFact,
  FlowCompletedFact,
  FlowCompleteEvent,
  FlowConcurrency,
  FlowConfig,
  FlowErrorEvent,
  FlowEvent,
  FlowFailedFact,
  FlowHooks,
  FlowIdOf,
  FlowInput,
  FlowOutput,
  FlowRefUpdatedFact,
  FlowStartEvent,
  FlowStartedFact,
  GlobalFact,
  InferSchemaInput,
  InferSchemaOutput,
  Json,
  LeaseReapedFact,
  LogEntry,
  Logger,
  LogLevel,
  MatchArm,
  MatchArmGuard,
  MatchArmOtherwise,
  MatchArmOutput,
  MatchArmSelectedFact,
  MatchArmShape,
  MatchGuardConfig,
  Millis,
  NeedRef,
  NeedsMap,
  NeedsOutputs,
  OnceRecordedFact,
  Operator,
  OperatorAuditOpts,
  OperatorRetryOpts,
  Optional,
  ParentLink,
  ParentRef,
  PrunableStatus,
  PruneOpts,
  PruneResult,
  QueryRunsOpts,
  QueryRunsResult,
  QueryRunsWhere,
  Queue,
  QueueDequeueOpts,
  QueueEnqueueOpts,
  QueueInspectEntry,
  QueueMessage,
  Register,
  ReplayMode,
  ReplayOpts,
  ResetScope,
  ResolvedConcurrency,
  ResolvedNeeds,
  RetryPolicy,
  RunEvent,
  RunEventEnvelope,
  RunEventTransport,
  RunStatus,
  RunSummary,
  SerializedError,
  SettleSignalResult,
  SignalBufferedFact,
  SignalConfig,
  SignalReceivedEvent,
  SignalReceivedFact,
  SnapshotGoneDisposition,
  SnapshotGonePolicy,
  StandardSchemaV1,
  Step,
  StepAbortRequestedFact,
  StepCanceledFact,
  StepCompletedFact,
  StepCompleteEvent,
  StepCtx,
  StepErrorEvent,
  StepEvent,
  StepFailedFact,
  StepId,
  StepKind,
  StepMap,
  StepOutput,
  StepResetFact,
  StepRetriedFact,
  StepRetryEvent,
  StepSkippedFact,
  StepStartEvent,
  StepStartedFact,
  StepStatus,
  Store,
  StreamEvent,
  StreamingStepCtx,
  StreamingTaskConfig,
  StreamTransport,
  StringKeyOf,
  SubflowConfig,
  SubflowStepOutput,
  TaskConfig,
  TimedOutSignal,
  Tx,
  Worker,
  WorkerConfig,
  WorkerRunOnceOpts,
  WorkerRunResult,
  WorkerRunUntilEmptyOpts,
} from "./types";
